### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by WenXin20** [BlueDuckYT/The-Outer-End#1]
`Minecraft v1.16.4`
`Forge v35.1.13`
`Outer End v0.1.1`

My server recently started crashing when the world loads, even though I had not visited the end in this world yet.
[Crash Report](https://gist.github.com/WenXin20/afbbdec4d4e1dc9508423aff456fa268)

**Comment by LudoCrypt** [comment]
The mod requires the Abnormals Core. https://www.curseforge.com/minecraft/mc-mods/abnormals-core make sure to have that in your mods folder

**Comment by WenXin20** [comment]
That was the version before it required abnormals. But the newest version works fine, so I'll go ahead and close this. :)
