### ISSUE TITLE
Crystal Crag biome chunks take significantly longer to render than do other biomes

### ISSUE THREAD

**Issue by Misticblade7** [BlueDuckYT/The-Outer-End#10]
Tested with OuterEnd-0.2.3 and abnormals_core-1.16.4-3.0.6

No other mods in use during testing.

**Comment by LudoCrypt** [comment]
We know, i am working on it as we speak

**Comment by Misticblade7** [comment]
Thanks! Beautiful mod btw <3

**Comment by BlueDuckYT** [comment]
Should be much more efficient now.
