### ISSUE TITLE
strange end generation

### ISSUE THREAD

**Issue by benbenlaw** [BlueDuckYT/The-Outer-End#19]
https://github.com/TelepathicGrunt/Bumblezone/issues/56

**Comment by BlueDuckYT** [comment]
Try installing Chocolate Fix.  If that does not fix it, post the issue to Abnormals Core's issue tracker, because they handle the biomes.

**Comment by benbenlaw** [comment]
chocolate fix did not work

**Comment by GiantLuigi4** [comment]
https://github.com/TelepathicGrunt/Bumblezone/issues/56#issuecomment-791484769
