### ISSUE TITLE
Grass generating in End

### ISSUE THREAD

**Issue by PseudonymousColby** [BlueDuckYT/The-Outer-End#20]
Hello, I'm having a problem a strange issue with the Outer End. I'm assuming it stems from a conflict with another mod, but I do not even know where to begin. Simply put, grass is generating in the Outer End biomes, and only Outer End biomes. Examples are below:

![2021-03-17_19 28 27](https://user-images.githubusercontent.com/30609492/111552522-e7c12a00-8758-11eb-8c7d-46f51f4f3337.png)

![2021-03-17_19 27 57](https://user-images.githubusercontent.com/30609492/111552532-eb54b100-8758-11eb-8068-335011f253f3.png)

Any help with this would be appreciated. It's not a game-breaking bug and I could live with it, but I would like to use this mod in its proper state rather than letting this change its appearance. Thanks!

**Comment by GiantLuigi4** [comment]
What mods do you have installed? It looks like tor some reason some mod is deciding to generate some overworld biome in the outer end biomes

**Comment by TelepathicGrunt** [comment]
@PseudonymousColby what biome is that grass biome? Also, have you updated abnormal core to very latest?
