### ISSUE TITLE
Blame report: Error loading registry data: Not a json array: 

### ISSUE THREAD

**Issue by pjlasl** [BlueDuckYT/The-Outer-End#24]
[ERROR] [co.te.bl.Blame/]:
****************** Blame Report 1.9.2 ******************
Failed to load resource file: outer_end:worldgen/processor_list/azure_wood.json
Reason stated: Not a json array
Possibly helpful hint (hopefully):
This error typically means you need an certain kind of JSON array surrounding
the current JSON. This is typically seen with worldgen JSON. If this is a worldgen JSON file, then
check out slicedlime's example datapack for worldgen to find what's off: https://t.co/cm3pJcAHcy?amp=1
Prettified form of the broken JSON:
{
"processor_type": "outer_end:if_loaded",
"modid": "quark",
"processor": {
"processor_type": "rule"
},
"forge:registry_name": "outer_end:azure_wood"
}
[ERROR] [minecraft/DynamicRegistries]: Error loading registry data: Not a json array: {"processor_type":"outer_end:if_loaded","modid":"quark","processor":{"processor_type":"rule"},"forge:registry_name":"outer_end:azure_wood"}

**Comment by TelepathicGrunt** [comment]
v0.2.9 Outer end now resolves this issue. You can close this report now
