### ISSUE TITLE
[Request] Config options for mob spawn weights

### ISSUE THREAD

**Issue by NJL5390** [BlueDuckYT/The-Outer-End#27]
Hello.

Firstly, Great work on the awesome mod, this really does add some worthwhile content to The End!

Secondly, I've noticed that when testing your latest update that some of your mobs such as the Chorus Squid and The Stalker spawn way too frequently. As a result, Mobs added to The End by other mods such as Alex's Mobs become practically extinct because of the extreme spawn frequency of these particular mobs from your mod. 

It would be great if we could customize the spawn weights of these mobs in the config so that modpack makers can adjust spawn weights accordingly depending on what other mods they have in their modpacks and to suit their needs for that particular modpack.

Thanks for the awesome mod and keep up the great work!

**Comment by BlueDuckYT** [comment]
Spawn weight has nothing to do with this issue but it is being looked into.

**Comment by NJL5390** [comment]
Do you need a log file or something similar to help you with this issue?

**Comment by BlueDuckYT** [comment]
Probably not, but i’ll lyk if we do.  Thanks!

**Comment by NJL5390** [comment]
May I make a couple of suggestions in relation to the Chorus Squid? 

Something I've noticed in relation to the Chorus squid is that it seems to attack anything and everything that isn't an enderman, including end mobs from other mods, it also seems to pursue mobs even from very far away, thus revealing itself quite quickly. 

Maybe the mobs it attack should be limited to those from this mod, so that it doesn't interfere with other mod's mobs?
It may also be a good idea to limit the range at which a chorus squid can pursue mobs to be quite small (Maybe 2-6 blocks) so that it doesn't reveal itself until it's prey is right next to it.  Thus making it's camouflage much more effective and making them much more able to catch players by surprise.

For example, You can see the one in the distance of this screenshot is already trying to pursue me, despite me being quite some distance from it, thus revealing itself way too early:
![2021-04-11_14 39 27](https://user-images.githubusercontent.com/64381954/114307097-0d322100-9ad6-11eb-9808-6473ed67fcf1.png)
Reducing this distance would help make the chorus squid's camouflage much more effective.

**Comment by NJL5390** [comment]
Thanks for fixing the mob issue! It works perfectly now!
