### ISSUE TITLE
BIG MOB ISSUE

### ISSUE THREAD

**Issue by celsiusqc** [BlueDuckYT/The-Outer-End#28]
![image](https://user-images.githubusercontent.com/63996164/114958397-e9057580-9e30-11eb-971b-68ad30c873f5.png)

You need to add spawn weight / limit option for the mobs as soon as possible since this is bad for servers and packs. The mobs spawn wayyy too much as you can see here

**Comment by NJL5390** [comment]
Try this version, it fixes the issue for me:
https://www.curseforge.com/minecraft/mc-mods/the-outer-end/files/3279238
