### ISSUE TITLE
Catacombs can spawn with nothing in them

### ISSUE THREAD

**Issue by Vazkii** [BlueDuckYT/The-Outer-End#29]
As seen:
![2021-04-18_21 12 44](https://user-images.githubusercontent.com/1794735/115159420-edc56600-a08a-11eb-8bfb-95c7daf9e84f.png)

**Comment by BlueDuckYT** [comment]
This is a rare occurrence due to how jigsaws work, but I’ll tweak the weights to make it less frequent

**Comment by Vazkii** [comment]
Tweaking the weights isn't the correct way to fix this, what you can instead do is change the way the jigsaws connect to not only guarantee a piece past the start piece, but to ensure corridors don't provide dead ends, but rather the dead ends are part of the pool that non-corridor pieces can pull from.

**Comment by BlueDuckYT** [comment]
This should be fixed now, I will push out a patch soon.
