### ISSUE TITLE
End Towers can generate in central end island

### ISSUE THREAD

**Issue by CerbTheOne** [BlueDuckYT/The-Outer-End#3]
I've been testing the new update and stumbled upon this seed in which there is an End Tower in the central island. The odds are probably insanely low, but it still breaks progression in the case that it does happen. You guys should probably look into if the same could happen with the new catacombs. I'm using the latest 0.2.1 with the latest Abnormals Core 3.0.6 and no other mods. Below is a screenshot and the seed, in case you want to check it out yourselves: *6908156887382285890*

![2021-01-09_22 09 38](https://user-images.githubusercontent.com/22283069/104113346-8ce20100-52d7-11eb-834a-da206302014e.png)

**Comment by BlueDuckYT** [comment]
This has been fixed
