### ISSUE TITLE
The Outer End (v0.2.11) Causing Start-Up Crashes for Singleplayer and Multiplayer Minecraft 1.16.5 (Forge 36.1.31)

### ISSUE THREAD

**Issue by MarioMario24680** [BlueDuckYT/The-Outer-End#44]
I can't run the latest version of The Outer End (version 0.2.11) on Minecraft 1.16.5 (Forge version 36.1.31), both client-side and server-side. It crashes as soon as I start up Minecraft. From what I could tell, the crashes started happening as soon as I updated Abnormals Core from version 3.1.1 to 3.2.0, and The Outer End depends on Abnormals Core to run. Could you please update the mod to work with the latest version of Abnormals Core?

Here's the client-side crash report: 
[crash-2021-06-14_00.31.22-fml.txt](https://github.com/BlueDuckYT/The-Outer-End/files/6645873/crash-2021-06-14_00.31.22-fml.txt)

Here's the server-side crash report: 
[crash-2021-06-14_00.29.00-fml.txt](https://github.com/BlueDuckYT/The-Outer-End/files/6645876/crash-2021-06-14_00.29.00-fml.txt)

Here's a list of other mods that I'm currently using alongside The Outer End:
[Good Mods.txt](https://github.com/BlueDuckYT/The-Outer-End/files/6645879/Good.Mods.txt)

**Comment by NJL5390** [comment]
I'm also getting this issue. It would be best to use the previous abnormals core version until the developer gets around to fixing this.

**Comment by BlueDuckYT** [comment]
Fixed in latest commit, will push out update to curseforge within the hour.
