### ISSUE TITLE
Crash when loading

### ISSUE THREAD

**Issue by vizthex123** [BlueDuckYT/The-Outer-End#45]
Not sure what's causing it. I installed MixinBootstrap (since it seems like the mod needs it), but that doesn't fix it.

Crash Report: 
[crash-2021-06-14_20.14.43-fml.txt](https://github.com/BlueDuckYT/The-Outer-End/files/6652076/crash-2021-06-14_20.14.43-fml.txt)

Game log:
[latest.log](https://github.com/BlueDuckYT/The-Outer-End/files/6652077/latest.log)

**Comment by Explode007** [comment]
same issue literally right now

**Comment by BlueDuckYT** [comment]
This is fixed in a new version not yet approved by curseforge.  Should be up within the next day or so, whenever curseforge gets to approving it.

**Comment by vizthex123** [comment]
Thanks for fixing it!
