### ISSUE TITLE
Game Crashes upon loading a world with Outer End and Endergetic Expansion installed

### ISSUE THREAD

**Issue by NJL5390** [BlueDuckYT/The-Outer-End#47]
Outer End Version: 0.2.12
Abnormals Core Version: 3.2.0
Forge Version: 36.1.31
Endergetic Expansion Version: 3.0.0
Crash Report: https://gist.github.com/NJL5390/317968df4d6279c87a1b223e9a4fddcb

After installing the latest version of Outer End alongside Endergetic Expansion, the game just crashes when attempting to load any world up. It seems to be related to Endergetic's tag for Ender Fire blocks. This issue does not occur without Outer End installed.

**Comment by Brun333rp** [comment]
that was my fault, I'm sorry

**Comment by BlueDuckYT** [comment]
Fixed
