### ISSUE TITLE
Outer End causing crash with Create mod

### ISSUE THREAD

**Issue by AlmightyChan** [BlueDuckYT/The-Outer-End#51]
[crash-2021-06-19_17.09.41-fml.txt](https://github.com/BlueDuckYT/The-Outer-End/files/6681437/crash-2021-06-19_17.09.41-fml.txt)

Seems that whenever I add this mod to a pack with Create in it I get this error. Removing Outer End prevents this. Removing Create also prevents this.

**Comment by BlueDuckYT** [comment]
This is an issue with Create and has already been reported here
