### ISSUE TITLE
crash between create and outer end on forge 36.1.10

### ISSUE THREAD

**Issue by dedreckoning** [BlueDuckYT/The-Outer-End#53]
hi i'm getting a crash report when loading a mod pack with create and outer end present. in the pack after the recent update. 

I am not sure if it is create or outer end causing the issue.

	Mod File: create-mc1.16.5_v0.3.1c.jar
	Failure message: Create (create) has failed to load correctly
		java.lang.ExceptionInInitializerError: null
	Mod Version: mc1.16.5_v0.3.1c+151
	Mod Issue URL: NOT PROVIDED
	Exception message: net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: create:block/palettes/outer_end:azure_window

thats the error it's throwing at me
any help would be greatly appreciated :)

**Comment by BlueDuckYT** [comment]
This is the third time this issue has been brought here.  This is on create’s side, we don’t interact with them at all.
