### ISSUE TITLE
end tower dungeons not generating

### ISSUE THREAD

**Issue by NixityNull** [BlueDuckYT/The-Outer-End#56]
I have located several end towers with the same problem: all the tunnels seem to be entirely dead ends with no loot or spawners. Do you know what the problem might be?

**Comment by BlueDuckYT** [comment]
Bad luck

**Comment by NixityNull** [comment]
> Bad luck

One or two times is bad luck.  This has happened 10, maybe 15 times. It cannot just be bad luck. Maybe it was a mod incompatibility or conflict, but it was bad luck. Regardless of if it is, if it WAS bad luck, it would still be an oversight on the mod's part, not mine. you should at least have scripted some sort of contingency, like allowing it to only generate if it has at least one loot room and one spawner. Heck, the chests aren't even generating in the top half, so the whole building is just a pointless waste.
