### ISSUE TITLE
mod fails to load correctly

### ISSUE THREAD

**Issue by Hautzii** [BlueDuckYT/The-Outer-End#57]
When I open the game, it says that the mod has failed to load correctly :
java.lang.NoClassDefFoundError: com/minecraftabnormals/abnormals_core/common/items/AbnormalsSignItem

I also have betterendforge and oh the biomes you'll go installed. May be a compatibility issue. 
I can also give you the logs if needed

**Comment by BlueDuckYT** [comment]
This is like the 5th time this has been reported here.  Use the latest version, this is fixed.
