### ISSUE TITLE
[Potential Bug] Bookshelves and chests in the catacombs aren't the Quark variants when Quark is installed

### ISSUE THREAD

**Issue by evanbones** [BlueDuckYT/The-Outer-End#6]
The bookshelves and chests generated are just normal oak instead of Poise, which would look much less out of place.

**Comment by BlueDuckYT** [comment]
I still have to set up the structures to switch to the quark stuff when it's installed

**Comment by Brun333rp** [comment]
The chests can be defined to generate there through Quark config, though this is not possible for Bookshelves
