### ISSUE TITLE
[Bug] Many items are missing tags

### ISSUE THREAD

**Issue by evanbones** [BlueDuckYT/The-Outer-End#7]
Azure Trapdoors for example are missing the following tags:

minecraft:trapdoors
minecraft:wooden_trapdoors

Azure Trapdoors are missing:
minecraft:slabs
minecraft:wooden_slabs

Vertical Slabs like Violite and Azure are missing:
quark:vertical_slabs

**Comment by BlueDuckYT** [comment]
Fixed now, will push a patch out fairly soon.
