### ISSUE TITLE
About ad

### ISSUE THREAD

**Issue by 800805** [BlueDuckYT/The-Outer-End#71]
Hello,I'm a Chinese Minecraft player.Can I advertise this wonderful mod to MCBBS(https://www.mcbbs.net) ?I'll let more people know it.MCBBS is the largest Minecraft forum in China,Many player are seeking good mods there.You know not all of them are good at English, they can't read your post (Even with Google translator) they need a Chinese translator.I'll mark you as the author.I'll NEVER claim it as mine, I just wanna translate it and let more people know it.Hope for your reply!Thank you!

**Comment by BlueDuckYT** [comment]
Go right ahead, as long as you link the curseforge page!
