### ISSUE TITLE
Typo on 1.20.1

### ISSUE THREAD

**Issue by mxnmnm** [BlueDuckYT/The-Outer-End#74]
![2024-01-16_20 22 17](https://github.com/BlueDuckYT/The-Outer-End/assets/8508976/223e84ed-0eee-43a1-9042-347ad3839bdc)

**Comment by BlueDuckYT** [comment]
Unplayable! I'll fix that in the next patch

**Comment by BlueDuckYT** [comment]
Fixed in 0.3.1
