### ISSUE TITLE
(1.20.1) Catacombs are not generating correctly and End towers are seemingly generateing with less treasure rooms

### ISSUE THREAD

**Issue by SillyGoblin** [BlueDuckYT/The-Outer-End#75]
Hi, I been toying around with the mod with my personal modpack and noticed some oddities with the structure generation. My time looking at the End towers has largely been anecdotal so far as I have only two instances of the structure spawning with very few rooms that have mob spawners, and i have not seen the rooms that would have blocks of ingots or the room with an end portal set up in it so far.

The Catacombs from what I'm seeing however are only spawning the entrance most of the time and it seems to not be generating that correctly.
![2024-01-16_22 04 43](https://github.com/BlueDuckYT/The-Outer-End/assets/78075413/b264e97f-9472-4a0c-93b4-5d2a6512d781)

![2024-01-16_22 04 49](https://github.com/BlueDuckYT/The-Outer-End/assets/78075413/ad2445ef-ff31-4a77-b227-557e4a1c6807)

If it does spawn with an actual layout it doesn't generate much side rooms, with the example here you'll see only one of them in the whole layout
![2024-01-16_22 15 42](https://github.com/BlueDuckYT/The-Outer-End/assets/78075413/4ac6a8b0-69da-49f2-874f-d85fd3b34471)

![2024-01-16_22 15 34](https://github.com/BlueDuckYT/The-Outer-End/assets/78075413/ba2c274c-6e56-48ad-8689-a4b45af5bd69)

this has been tested with 
forge 47.2.0 for 1.20.1 
Blueprint 7.0.0 for 1.20.1
Outer End 0.3 for 1.20.1

**Comment by BlueDuckYT** [comment]
Catacombs bug is known and will be fixed in the next patch. As for the lack of rooms in the towers, I'm planning on tweaking the structure weights to allow for more of them. The end portal room is supposed to be very rare.

**Comment by SillyGoblin** [comment]
Ah I see, everything seems to be better with the update so far. I do appreciate the work, and hope working on this wont give you too much of a headache.
