### ISSUE TITLE
[Bug] Pickaxes not working correctly in the 1.20.1 update

### ISSUE THREAD

**Issue by adozenlionsroaring** [BlueDuckYT/The-Outer-End#76]
I've just installed the new Outer End update (alongside Blueprint) for 1.20.1, but I've found that my pickaxes are no longer breaking blocks properly (eg. a Netherite pickaxe with Efficiency V is taking forever to get through a single block of Netherrack, which definitely shouldn't be happening lol). The problem goes away when I remove the mod. I am playing on Forge 47.2.0.

**Comment by BlueDuckYT** [comment]
Fixed in 0.3.1
