### ISSUE TITLE
[1.20.1] Crystals have improper rendering for transparent objects

### ISSUE THREAD

**Issue by Reshy** [BlueDuckYT/The-Outer-End#80]
![image](https://github.com/BlueDuckYT/The-Outer-End/assets/2096384/10099012-4a4a-4dfa-8671-c3232291933d)
![image](https://github.com/BlueDuckYT/The-Outer-End/assets/2096384/2332f5e2-c8d2-4752-b7f7-4f909747e522)
![image](https://github.com/BlueDuckYT/The-Outer-End/assets/2096384/18378141-daa1-4cc8-be5a-f42030527aa3)
![image](https://github.com/BlueDuckYT/The-Outer-End/assets/2096384/e9e4e697-c791-4310-a750-0e595a7ac2c8)
![image](https://github.com/BlueDuckYT/The-Outer-End/assets/2096384/0a23b8d7-3f31-4d89-806e-0ab387157c6d)

Side by side you can see there's rendering errors with how the crystals render, which causes a performance hit as well as some minor artifacting.

**Comment by BlueDuckYT** [comment]
This will be fixed in the next release

**Comment by BlueDuckYT** [comment]
Forgot to close this
