### ISSUE TITLE
Current update breaks the planks tag

### ISSUE THREAD

**Issue by Wise-Cactus** [BlueDuckYT/The-Outer-End#83]
![2024-02-10_02 26 25](https://github.com/BlueDuckYT/The-Outer-End/assets/159611058/a284e268-e77c-415f-86af-5fd811512143)

The issue is self-explanatory; something in the update on February 9th, 2024 manage to break the planks tag, making anything using planks uncraftable. This screenshot shows a bed recipe with just Outer End and JEI

**Comment by BlueDuckYT** [comment]
Fixed in 1.0.1
