### ISSUE TITLE
[1.0.3] Crashing on startup

### ISSUE THREAD

**Issue by ChapperNi** [BlueDuckYT/The-Outer-End#84]
This only happens with The Outer End in my mods folder.

[crash-2024-01-29_22.12.33-client.txt](https://github.com/BlueDuckYT/The-Outer-End/files/14232707/crash-2024-01-29_22.12.33-client.txt)

**Comment by BlueDuckYT** [comment]
Try installing blueprint

**Comment by ChapperNi** [comment]
Awesome response time!
Sadly, installing blueprint now gives a different error
[Uploading crash-2024-01-29_22.12.33-client.txt…]()

**Comment by BlueDuckYT** [comment]
That link doesn't seem to work, can you resend it?

**Comment by ChapperNi** [comment]
[crash-2024-02-11_06.26.12-client.txt](https://github.com/BlueDuckYT/The-Outer-End/files/14234903/crash-2024-02-11_06.26.12-client.txt)

**Comment by BlueDuckYT** [comment]
Sorry for the late response but it doesn't seem like this crash is the fault of The Outer End
