### ISSUE TITLE
[1.20.1] Beehives tag is broken

### ISSUE THREAD

**Issue by WenXin20** [BlueDuckYT/The-Outer-End#85]
```
Minecraft v1.20.1
Outer End v1.0.3
```

The vanilla beehives tag is currently broken according to the latest.log: 
`Couldn't load tag minecraft:beehives as it is missing following references: outer_end:azure_beehive (from TheOuterEnd-1.0.3.jar)`

**Comment by BlueDuckYT** [comment]
I’ll put out a patch tomorrow to fix this

**Comment by WenXin20** [comment]
Thanks!

**Comment by BlueDuckYT** [comment]
Just posted the patch, just waiting for curseforge approval.
