### ISSUE TITLE
Mod failes do load correctly 

### ISSUE THREAD

**Issue by justskrill** [BlueDuckYT/The-Outer-End#86]
![Bild_2024-02-21_114515892](https://github.com/BlueDuckYT/The-Outer-End/assets/160507102/f1afff41-3da4-4289-8801-eb8fc6163d73)

**Comment by BlueDuckYT** [comment]
Install blueprint

**Comment by justskrill** [comment]
> Install blueprint

still not working installed the latest version but 
![Bild_2024-03-02_102200261](https://github.com/BlueDuckYT/The-Outer-End/assets/160507102/39604bef-3d07-4ad9-9115-28c6a29ed3de)

**Comment by BlueDuckYT** [comment]
Install the second to latest version, new version introduces breaking changes

**Comment by BlueDuckYT** [comment]
Fixed in 1.0.6
