### ISSUE TITLE
Issue with Blueprint and The Outer End on start-up

### ISSUE THREAD

**Issue by foxxonox** [BlueDuckYT/The-Outer-End#87]
Hi! I'm trying to make my own modpack with The Outer End in it, and I can't figure out this error I'm getting. When the game is loading, it stops with this picture & errors 
![modpack error](https://github.com/BlueDuckYT/The-Outer-End/assets/161883011/723056ff-6041-4263-acc8-7b65547fd4db)
I have the latest log file and crash report as well. I checked with the Modded Minecraft discord server and they said its definitely an issue with The Outer End mod, since Blueprint is a library mod for The Outer End. 
[crash-2024-03-01_13.30.45-fml.txt](https://github.com/BlueDuckYT/The-Outer-End/files/14465312/crash-2024-03-01_13.30.45-fml.txt)
[latest.log](https://github.com/BlueDuckYT/The-Outer-End/files/14465316/latest.log)

Hopefully I've provided enough information, if anyone is able to help me figure out what's wrong, I'd really appreciate it!

**Comment by BlueDuckYT** [comment]
Looks like Blueprint released an update yesterday containing a breaking change, for now revert to the previous blueprint version but I'll put out a patch very soon to fix this

**Comment by foxxonox** [comment]
Thank you! I'll do that

**Comment by BlueDuckYT** [comment]
Version 1.0.6 should work with the latest Blueprint version now
