### ISSUE TITLE
Mod not loading at all

### ISSUE THREAD

**Issue by Finnodile** [BlueDuckYT/The-Outer-End#98]
I'm using Forge 1.20.1 with the mod in my mods folder. It gave me the error "java.lang.NoClassDefFoundError" and "com/teamabnormals/blueprint/core/util/registry/RegistryHelper"
![image](https://github.com/user-attachments/assets/47e02706-ad6a-4b21-b41b-bffa71fe3f18)

**Comment by BlueDuckYT** [comment]
Install Blueprint
